=== api-evangelist/amazon-route53-resolver/json-schema/amazon-route53-resolver-openapi-resolver-rule-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-route53-resolver/refs/heads/main/json-schema/amazon-route53-resolver-openapi-resolver-rule-schema.json",
  "title": "ResolverRule",
  "description": "For queries that originate in your VPC, detailed information about a Resolver rule, which specifies how to route DNS queries out of the VPC. The <code>ResolverRule</code> parameter appears in the response to a <a href=\"https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverRule.html\">CreateResolverRule</a>, <a href=\"https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverRule.html\">DeleteResolverRule</a>, <a href=\"https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRule.html\">GetResolverRule</a>, <a href=\"https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverRules.html\">ListResolverRules</a>, or <a href=\"https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverRule.html\">UpdateResolverRule</a> request.",
  "type": "object",
  "properties": {
    "Id": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceId"
        },
        {
          "description": "The ID that Resolver assigned to the Resolver rule when you created it."
        }
      ]
    },
    "CreatorRequestId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CreatorRequestId"
        },
        {
          "description": "A unique string that you specified when you created the Resolver rule. <code>CreatorRequestId</code> identifies the request and allows failed requests to be retried without the risk of running the operation twice. "
        }
      ]
    },
    "Arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The ARN (Amazon Resource Name) for the Resolver rule specified by <code>Id</code>."
        }
      ]
    },
    "DomainName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DomainName"
        },
        {
          "description": "DNS queries for this domain name are forwarded to the IP addresses that are specified in <code>TargetIps</code>. If a query matches multiple Resolver rules (example.com and www.example.com), the query is routed using the Resolver rule that contains the most specific domain name (www.example.com)."
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResolverRuleStatus"
        },
        {
          "description": "A code that specifies the current status of the Resolver rule."
        }
      ]
    },
    "StatusMessage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusMessage"
        },
        {
          "description": "A detailed description of the status of a Resolver rule."
        }
      ]
    },
    "RuleType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RuleTypeOption"
        },
        {
          "description": "<p>When you want to forward DNS queries for specified domain name to resolvers on your network, specify <code>FORWARD</code>.</p> <p>When you have a forwarding rule to forward DNS queries for a domain to your network and you want Resolver to process queries for a subdomain of that domain, specify <code>SYSTEM</code>.</p> <p>For example, to forward DNS queries for example.com to resolvers on your network, you create a rule and specify <code>FORWARD</code> for <code>RuleType</code>. To then have Resolver process queries for apex.example.com, you create a rule and specify <code>SYSTEM</code> for <code>RuleType</code>.</p> <p>Currently, only Resolver can create rules that have a value of <code>RECURSIVE</code> for <code>RuleType</code>.</p>"
        }
      ]
    },
    "Name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The name for the Resolver rule, which you specified when you created the Resolver rule."
        }
      ]
    },
    "TargetIps": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TargetList"
        },
        {
          "description": "An array that contains the IP addresses and ports that an outbound endpoint forwards DNS queries to. Typically, these are the IP addresses of DNS resolvers on your network. Specify IPv4 addresses. IPv6 is not supported."
        }
      ]
    },
    "ResolverEndpointId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceId"
        },
        {
          "description": "The ID of the endpoint that the rule is associated with."
        }
      ]
    },
    "OwnerId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AccountId"
        },
        {
          "description": "When a rule is shared with another Amazon Web Services account, the account ID of the account that the rule is shared with."
        }
      ]
    },
    "ShareStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ShareStatus"
        },
        {
          "description": "Whether the rule is shared and, if so, whether the current account is sharing the rule with another account, or another account is sharing the rule with the current account."
        }
      ]
    },
    "CreationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Rfc3339TimeString"
        },
        {
          "description": "The date and time that the Resolver rule was created, in Unix time format and Coordinated Universal Time (UTC)."
        }
      ]
    },
    "ModificationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Rfc3339TimeString"
        },
        {
          "description": "The date and time that the Resolver rule was last updated, in Unix time format and Coordinated Universal Time (UTC)."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-route53-resolver/examples/amazon-route53-resolver-openapi-resolver-rule-example.json
{
  "Id": "abc123",
  "CreatorRequestId": "abc123",
  "Arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "DomainName": "example.com",
  "Status": "ACTIVE",
  "StatusMessage": "ACTIVE",
  "RuleType": "example-value",
  "Name": "Example Resource",
  "TargetIps": "example-value",
  "ResolverEndpointId": "abc123"
}
